services:
  app:
    image: alfakids:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Mapeie a porta usada pela aplicação
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: alfaKidsDb
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@db:5432/alfaKidsDb
    depends_on:
      - db # Garante que o banco estará disponível antes da aplicação iniciar
    command: >
      sh -c "
      flask db upgrade &&
      python3 -m flask run --host=0.0.0.0"
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-container
    restart: always
    ports:
      - "5432:5432" # Porta do PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: alfaKidsDb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge