"""Initial Migration

Revision ID: 116a815744e0
Revises: 
Create Date: 2024-12-10 12:27:43.951708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116a815744e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('registration', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('registration')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.Column('autism_level', sa.Integer(), nullable=False),
    sa.Column('school_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accountable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=120), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_student'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id_subject', sa.Integer(), nullable=False),
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.id'], ),
    sa.ForeignKeyConstraint(['id_subject'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_distribution',
    sa.Column('id_activity', sa.Integer(), nullable=False),
    sa.Column('id_classroom', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_activity'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['id_classroom'], ['classroom.id'], ),
    sa.PrimaryKeyConstraint('id_activity', 'id_classroom')
    )
    op.create_table('class_allocation',
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('id_classroom', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_classroom'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id_student', 'id_classroom')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('id_activity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_activity'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discursive_question',
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_question'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id_question')
    )
    op.create_table('objective_question',
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('answer1', sa.String(length=120), nullable=False),
    sa.Column('answer2', sa.String(length=120), nullable=False),
    sa.Column('answer3', sa.String(length=120), nullable=False),
    sa.Column('answer4', sa.String(length=120), nullable=False),
    sa.Column('right_answer', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['id_question'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id_question')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objective_question')
    op.drop_table('discursive_question')
    op.drop_table('question')
    op.drop_table('class_allocation')
    op.drop_table('activity_distribution')
    op.drop_table('classroom')
    op.drop_table('activity')
    op.drop_table('accountable')
    op.drop_table('subject')
    op.drop_table('student')
    op.drop_table('professor')
    # ### end Alembic commands ###
