"""Students Accomplishments table creation

Revision ID: 4a31abf53647
Revises: 116a815744e0
Create Date: 2025-01-12 14:24:50.636499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a31abf53647'
down_revision = '116a815744e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_accomplishment',
    sa.Column('id_activity', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_activity'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id_activity', 'id_student')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_accomplishment')
    # ### end Alembic commands ###
