"""Subject Column Adjustment

Revision ID: 644b5c3a6e06
Revises: 41097fef24a1
Create Date: 2024-12-09 14:03:19.457706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644b5c3a6e06'
down_revision = '41097fef24a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_unique_constraint('name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint('name', type_='unique')

    # ### end Alembic commands ###
