"""Students Answers adjustment

Revision ID: c56ed07933c3
Revises: 3e664d5c7d19
Create Date: 2025-01-13 14:55:08.552306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56ed07933c3'
down_revision = '3e664d5c7d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_student', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'student', ['id_student'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_student')

    # ### end Alembic commands ###
