"""Table name adjusment

Revision ID: f557f38bdeea
Revises: 93d03fe9b3f5
Create Date: 2024-12-05 09:56:46.927266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f557f38bdeea'
down_revision = '93d03fe9b3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_discursive',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_objective',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('answer1', sa.String(length=120), nullable=False),
    sa.Column('answer2', sa.String(length=120), nullable=False),
    sa.Column('answer3', sa.String(length=120), nullable=False),
    sa.Column('answer4', sa.String(length=120), nullable=False),
    sa.Column('right_answer', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('objective')
    op.drop_table('discursive')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discursive',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id_professor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expected_answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.id'], name='discursive_id_professor_fkey'),
    sa.PrimaryKeyConstraint('id', name='discursive_pkey')
    )
    op.create_table('objective',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id_professor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer1', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('answer2', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('answer3', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('answer4', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('right_answer', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.id'], name='objective_id_professor_fkey'),
    sa.PrimaryKeyConstraint('id', name='objective_pkey')
    )
    op.drop_table('activity_objective')
    op.drop_table('activity_discursive')
    # ### end Alembic commands ###
